name: aoc_2022
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.3.0
  lints: ^2.0.0
